{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "web-application",
    "version": "0.74.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.74.0.jar",
          "url": "web-application-0.74.0.jar",
          "size": 10636,
          "sha512": "d0fe2ae7815b2bbbd3c450af300ab171111cca0b4580b1b879f71ea1713211f5f50a75e413cce0f989ffc8e4cb8144445fc19a36a635efc29d0b7db73c1fff42",
          "sha256": "0065331cdbe1b6851fcd2e0ebe5ce83beb720ea24420a7ce94072cdf004fe30c",
          "sha1": "f68259f56535d35f2dde290b1ea90593bcb8d9fe",
          "md5": "4e73f90c8dfa71bfcbe4d5db53d7c630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.74.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.74.0.jar",
          "url": "web-application-0.74.0.jar",
          "size": 10636,
          "sha512": "d0fe2ae7815b2bbbd3c450af300ab171111cca0b4580b1b879f71ea1713211f5f50a75e413cce0f989ffc8e4cb8144445fc19a36a635efc29d0b7db73c1fff42",
          "sha256": "0065331cdbe1b6851fcd2e0ebe5ce83beb720ea24420a7ce94072cdf004fe30c",
          "sha1": "f68259f56535d35f2dde290b1ea90593bcb8d9fe",
          "md5": "4e73f90c8dfa71bfcbe4d5db53d7c630"
        }
      ]
    }
  ]
}
