{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "web-application",
    "version": "0.126.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.126.0.jar",
          "url": "web-application-0.126.0.jar",
          "size": 13975,
          "sha512": "ad6843921b8dcdd792bc79796e43c0d3dfe969559b7ab205ad0cda3d9b0002b72e787370866da13585057b56e22fc6ed491d2eb7f7111915844d04f9f0435ae7",
          "sha256": "35a8c818c8069268a07ce17fff30a0ee111e0e458dc3d65b620ce7acfc5af093",
          "sha1": "741fb7bfaea1b763e7d30f92b9a57e3985467d9f",
          "md5": "4be040d27f8ca7ed4b437a50cae5cc16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.126.0.jar",
          "url": "web-application-0.126.0.jar",
          "size": 13975,
          "sha512": "ad6843921b8dcdd792bc79796e43c0d3dfe969559b7ab205ad0cda3d9b0002b72e787370866da13585057b56e22fc6ed491d2eb7f7111915844d04f9f0435ae7",
          "sha256": "35a8c818c8069268a07ce17fff30a0ee111e0e458dc3d65b620ce7acfc5af093",
          "sha1": "741fb7bfaea1b763e7d30f92b9a57e3985467d9f",
          "md5": "4be040d27f8ca7ed4b437a50cae5cc16"
        }
      ]
    }
  ]
}
