{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "resource-packaging",
    "version": "0.126.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.126.0.jar",
          "url": "resource-packaging-0.126.0.jar",
          "size": 28557,
          "sha512": "540f6f0334b179cf1d11ceff36ace3745c6a097031bca1738121db446141d7636bfacd5c209f284b7fae171d39011f8c88d0fba4643cd63e805c4da1f6ab7fa2",
          "sha256": "1a3351605e129f4b5af541a3ee598bef619192dfe5c5a287a27ffc04fa029e0e",
          "sha1": "227220304b1df13cf123631ebe8e362e143c0d72",
          "md5": "4a1ad4dcf3343a8d2393cd03f01b08bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.126.0.jar",
          "url": "resource-packaging-0.126.0.jar",
          "size": 28557,
          "sha512": "540f6f0334b179cf1d11ceff36ace3745c6a097031bca1738121db446141d7636bfacd5c209f284b7fae171d39011f8c88d0fba4643cd63e805c4da1f6ab7fa2",
          "sha256": "1a3351605e129f4b5af541a3ee598bef619192dfe5c5a287a27ffc04fa029e0e",
          "sha1": "227220304b1df13cf123631ebe8e362e143c0d72",
          "md5": "4a1ad4dcf3343a8d2393cd03f01b08bf"
        }
      ]
    }
  ]
}
