{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "web-application",
    "version": "0.130.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.130.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.130.0.jar",
          "url": "web-application-0.130.0.jar",
          "size": 13973,
          "sha512": "bdde9a5a7cd8df5cc7f80c20e42aff9721bb9e512fd92f13fc8fc3efe2ab0eacb2d054b6c925a71005f7ee15ea41249d373b19d84a48a6e8058b0000b3369588",
          "sha256": "9e84536b8fd6732c745d680dba7b815ff84aad467edab73b9507df26de4ebe79",
          "sha1": "7292aad6552413503c1805052b4792284d6f734c",
          "md5": "e8cc2f923a9eee863e7553bc4b909e6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.130.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.130.0.jar",
          "url": "web-application-0.130.0.jar",
          "size": 13973,
          "sha512": "bdde9a5a7cd8df5cc7f80c20e42aff9721bb9e512fd92f13fc8fc3efe2ab0eacb2d054b6c925a71005f7ee15ea41249d373b19d84a48a6e8058b0000b3369588",
          "sha256": "9e84536b8fd6732c745d680dba7b815ff84aad467edab73b9507df26de4ebe79",
          "sha1": "7292aad6552413503c1805052b4792284d6f734c",
          "md5": "e8cc2f923a9eee863e7553bc4b909e6a"
        }
      ]
    }
  ]
}
