{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "spring",
    "version": "0.126.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.126.0.jar",
          "url": "spring-0.126.0.jar",
          "size": 17566,
          "sha512": "9d000a4ddc4436ec3e27890208f232fe64a7f979282a33ed626bac44e086ea2f7272d2225089703510b10a69dfcc75b58a9333b905b343cff25f5a22658282c4",
          "sha256": "b5ef1d11e17012d07c12819c1894ef34d86d47defeae8dfada975d7115ebe3a5",
          "sha1": "2cb420cb338e0173c44a130bfc258740c53a2d9b",
          "md5": "a1e53f0a49e268fda802c4c47f337fcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.126.0.jar",
          "url": "spring-0.126.0.jar",
          "size": 17566,
          "sha512": "9d000a4ddc4436ec3e27890208f232fe64a7f979282a33ed626bac44e086ea2f7272d2225089703510b10a69dfcc75b58a9333b905b343cff25f5a22658282c4",
          "sha256": "b5ef1d11e17012d07c12819c1894ef34d86d47defeae8dfada975d7115ebe3a5",
          "sha1": "2cb420cb338e0173c44a130bfc258740c53a2d9b",
          "md5": "a1e53f0a49e268fda802c4c47f337fcc"
        }
      ]
    }
  ]
}
