{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.126.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.126.0.jar",
          "url": "jvm-application-0.126.0.jar",
          "size": 67819,
          "sha512": "548556cfaf9c18e4ed47a9f5b6166ab5f39b83e2804ee3f1093dc8f5d1d3cdd4ce3ecbddc72d96332357a87bcd4cddd0da3d612a0120c56af9605c17c429c772",
          "sha256": "5f444ad475d63203dbd5f05cd5eb585af31a10ebc4a10efad70e0d51e052d34f",
          "sha1": "28b431e23d947e16b8e410db0e150cdac94f0686",
          "md5": "75c764c861acc4d8e04af3c8bdd188d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.126.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.126.0.jar",
          "url": "jvm-application-0.126.0.jar",
          "size": 67819,
          "sha512": "548556cfaf9c18e4ed47a9f5b6166ab5f39b83e2804ee3f1093dc8f5d1d3cdd4ce3ecbddc72d96332357a87bcd4cddd0da3d612a0120c56af9605c17c429c772",
          "sha256": "5f444ad475d63203dbd5f05cd5eb585af31a10ebc4a10efad70e0d51e052d34f",
          "sha1": "28b431e23d947e16b8e410db0e150cdac94f0686",
          "md5": "75c764c861acc4d8e04af3c8bdd188d6"
        }
      ]
    }
  ]
}
