{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.123.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.123.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.123.0.jar",
          "url": "jvm-application-0.123.0.jar",
          "size": 67803,
          "sha512": "4735ffc8af813eb6106748687c78ebf2d9f0ab451cfef26e0799d89340ef5464a6557c9e93dda4bc8b400ef135c2a2a0a6ce8bbb26f8430982ce0aa18c769e78",
          "sha256": "2c629f3b9edb2e66c8afc7af819a96f58c63bd26db63cebfd5db97a09fa44147",
          "sha1": "48b143e9e33ceb4f51c57ba9ff2e8c9d74ffcc79",
          "md5": "8e5c70ae50cf152fc616430950b1af89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.123.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.123.0.jar",
          "url": "jvm-application-0.123.0.jar",
          "size": 67803,
          "sha512": "4735ffc8af813eb6106748687c78ebf2d9f0ab451cfef26e0799d89340ef5464a6557c9e93dda4bc8b400ef135c2a2a0a6ce8bbb26f8430982ce0aa18c769e78",
          "sha256": "2c629f3b9edb2e66c8afc7af819a96f58c63bd26db63cebfd5db97a09fa44147",
          "sha1": "48b143e9e33ceb4f51c57ba9ff2e8c9d74ffcc79",
          "md5": "8e5c70ae50cf152fc616430950b1af89"
        }
      ]
    }
  ]
}
