{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.130.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.130.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.130.0.jar",
          "url": "jvm-application-0.130.0.jar",
          "size": 67820,
          "sha512": "4509be297aa30577d260c58be61762c2f768461bf90c80345eeac90bf6f753710f82bf383955b433cd4f1f3637c2165895ba8f0c877c452b8de63c2c632669b6",
          "sha256": "767571c964b4a9b7d0c82e76be3c8463554c38887e024e32e69f6746363c03fc",
          "sha1": "f1958438237ae8b39b780ee37a07ec791b94dbb7",
          "md5": "1b757cd0c9362a0251aad0b48cf3a3c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.130.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.130.0.jar",
          "url": "jvm-application-0.130.0.jar",
          "size": 67820,
          "sha512": "4509be297aa30577d260c58be61762c2f768461bf90c80345eeac90bf6f753710f82bf383955b433cd4f1f3637c2165895ba8f0c877c452b8de63c2c632669b6",
          "sha256": "767571c964b4a9b7d0c82e76be3c8463554c38887e024e32e69f6746363c03fc",
          "sha1": "f1958438237ae8b39b780ee37a07ec791b94dbb7",
          "md5": "1b757cd0c9362a0251aad0b48cf3a3c1"
        }
      ]
    }
  ]
}
