{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.93.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.93.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.93.0.jar",
          "url": "jvm-application-0.93.0.jar",
          "size": 66767,
          "sha512": "64e5c65ff000934cac3dd91f0d160901cc1e41f2a2120da120272321042fcff6e16e0ad9cbc1850a43fb7319a5df88278400bf7ae5c078bfbac83fbe1716b8bc",
          "sha256": "25041854caee23eca5485c4c480d143aef98cc7a5fa2ab96ec0137e828d5643a",
          "sha1": "a0183d1930fe16f092beb97c174e1846ef3063ff",
          "md5": "6ab8cef749080cef3e68fc2007dfe90d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.93.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.93.0.jar",
          "url": "jvm-application-0.93.0.jar",
          "size": 66767,
          "sha512": "64e5c65ff000934cac3dd91f0d160901cc1e41f2a2120da120272321042fcff6e16e0ad9cbc1850a43fb7319a5df88278400bf7ae5c078bfbac83fbe1716b8bc",
          "sha256": "25041854caee23eca5485c4c480d143aef98cc7a5fa2ab96ec0137e828d5643a",
          "sha1": "a0183d1930fe16f092beb97c174e1846ef3063ff",
          "md5": "6ab8cef749080cef3e68fc2007dfe90d"
        }
      ]
    }
  ]
}
