{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "spring",
    "version": "0.84.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.84.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.84.0.jar",
          "url": "spring-0.84.0.jar",
          "size": 17237,
          "sha512": "2c7302fa8f8f82b9f2757180425d444d56f3b71852d2318c0de33391b30177d4e5e14ccb7b8d2b95e7852df03a53468d763d561bf626d1f99e0ed19058999431",
          "sha256": "3654f9cbb4506094af5ce92a08f311de268c6dd2d1a2b630a396e5a378c61cc4",
          "sha1": "b37cb564181e5c8bd6b1d7922109ee613cb3c8a9",
          "md5": "2f208dde4e18a08cab57916246a5ed85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.84.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.84.0.jar",
          "url": "spring-0.84.0.jar",
          "size": 17237,
          "sha512": "2c7302fa8f8f82b9f2757180425d444d56f3b71852d2318c0de33391b30177d4e5e14ccb7b8d2b95e7852df03a53468d763d561bf626d1f99e0ed19058999431",
          "sha256": "3654f9cbb4506094af5ce92a08f311de268c6dd2d1a2b630a396e5a378c61cc4",
          "sha1": "b37cb564181e5c8bd6b1d7922109ee613cb3c8a9",
          "md5": "2f208dde4e18a08cab57916246a5ed85"
        }
      ]
    }
  ]
}
