{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "web-application",
    "version": "0.102.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.102.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.102.0.jar",
          "url": "web-application-0.102.0.jar",
          "size": 13811,
          "sha512": "16b579adef7466e9698e6650a60ceef7de74699ce7343b5e5e34df49bf1ac3de6f39ce8e475c83f3899eecc855c3f5c5b29dc4c94b2adfef28ad4be96eb920c8",
          "sha256": "76581f137fb67574dfba9d1915c6011d29005f5b48a41f7243d443339f7719bb",
          "sha1": "cd50cffc70797fa21c6b11840212da8a63683989",
          "md5": "5beb1112f67f8e0504561ae7302ce6af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.102.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.102.0.jar",
          "url": "web-application-0.102.0.jar",
          "size": 13811,
          "sha512": "16b579adef7466e9698e6650a60ceef7de74699ce7343b5e5e34df49bf1ac3de6f39ce8e475c83f3899eecc855c3f5c5b29dc4c94b2adfef28ad4be96eb920c8",
          "sha256": "76581f137fb67574dfba9d1915c6011d29005f5b48a41f7243d443339f7719bb",
          "sha1": "cd50cffc70797fa21c6b11840212da8a63683989",
          "md5": "5beb1112f67f8e0504561ae7302ce6af"
        }
      ]
    }
  ]
}
