{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "resource-packaging",
    "version": "0.117.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.117.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.117.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.117.0.jar",
          "url": "resource-packaging-0.117.0.jar",
          "size": 28547,
          "sha512": "5f6dbc3f8e0815b0345be31da5075d7feb471ce2b119c5efba16973ed7e1f4fabed252f728f85a0859bc48d7217f5cbb2d10490597bba7a6c5f9b5127f1d182d",
          "sha256": "a10f84d44a0c8552b97c65550354744e5d1c03cbad4f3911e04f04c14fdd1f3e",
          "sha1": "d6927ae4c71c149db5a0e87c4bd3999bc90812a1",
          "md5": "d0b96582ae3a170f008365f9180a75f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.117.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.117.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.117.0.jar",
          "url": "resource-packaging-0.117.0.jar",
          "size": 28547,
          "sha512": "5f6dbc3f8e0815b0345be31da5075d7feb471ce2b119c5efba16973ed7e1f4fabed252f728f85a0859bc48d7217f5cbb2d10490597bba7a6c5f9b5127f1d182d",
          "sha256": "a10f84d44a0c8552b97c65550354744e5d1c03cbad4f3911e04f04c14fdd1f3e",
          "sha1": "d6927ae4c71c149db5a0e87c4bd3999bc90812a1",
          "md5": "d0b96582ae3a170f008365f9180a75f2"
        }
      ]
    }
  ]
}
