{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "resource-packaging",
    "version": "0.114.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.114.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.114.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.114.0.jar",
          "url": "resource-packaging-0.114.0.jar",
          "size": 28324,
          "sha512": "18020e1fdd72cbd1b3cffa42552fc142a3e9018c6e25ac94089d2d04ca985ca7644485d3163356e0896f5cacf9cd2bad9ce8ad5e4d8520f946ca85f68d5726a5",
          "sha256": "3d1fbc0894cd73712b2ae6f3f5bdd86b8279308670dd7738f47834ec5052182d",
          "sha1": "16da09f1dbc42c726cab8c9116ece13efe1248b6",
          "md5": "d885e84377307cad507cff8a7b0b36dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.114.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.114.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.114.0.jar",
          "url": "resource-packaging-0.114.0.jar",
          "size": 28324,
          "sha512": "18020e1fdd72cbd1b3cffa42552fc142a3e9018c6e25ac94089d2d04ca985ca7644485d3163356e0896f5cacf9cd2bad9ce8ad5e4d8520f946ca85f68d5726a5",
          "sha256": "3d1fbc0894cd73712b2ae6f3f5bdd86b8279308670dd7738f47834ec5052182d",
          "sha1": "16da09f1dbc42c726cab8c9116ece13efe1248b6",
          "md5": "d885e84377307cad507cff8a7b0b36dd"
        }
      ]
    }
  ]
}
