{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "spring",
    "version": "0.131.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.131.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.131.0.jar",
          "url": "spring-0.131.0.jar",
          "size": 17565,
          "sha512": "5599c18706bcee66d32ea1381bcbc77b9fdefef70f30a3f540497c120668a5cfbf7f734b0247f03bf431e22a409bea8ec30ad7b37003f7c6fbd7a2da2e1f4e3d",
          "sha256": "1d5525d79fba717c8dc064293a5656205903a7823d25501c8e857de517febedf",
          "sha1": "c0c351794bb36b6742238aa7c361e44af967e4e2",
          "md5": "6a3b5677f916cb9b5167bf8ada755208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.131.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "spring-0.131.0.jar",
          "url": "spring-0.131.0.jar",
          "size": 17565,
          "sha512": "5599c18706bcee66d32ea1381bcbc77b9fdefef70f30a3f540497c120668a5cfbf7f734b0247f03bf431e22a409bea8ec30ad7b37003f7c6fbd7a2da2e1f4e3d",
          "sha256": "1d5525d79fba717c8dc064293a5656205903a7823d25501c8e857de517febedf",
          "sha1": "c0c351794bb36b6742238aa7c361e44af967e4e2",
          "md5": "6a3b5677f916cb9b5167bf8ada755208"
        }
      ]
    }
  ]
}
