{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.67.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.67.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.67.0.jar",
          "url": "jvm-application-0.67.0.jar",
          "size": 67541,
          "sha512": "2437404702b78f48f1fb76293992b93cbfca99b7bdea2501c4f8228535785730e2672a7c4f4e2441ce1539940b4613b05b4483ed6444474383d966a9453852f8",
          "sha256": "ef12f37c72fe20484583bfe8f10d795ed2ddd1de572ec7600cb36c1a284c3225",
          "sha1": "63b0b9ed3f8ef1001d61ae0b1873066130032ba4",
          "md5": "89bbde8466ab05952f6bfc3dff6a9647"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.67.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.67.0.jar",
          "url": "jvm-application-0.67.0.jar",
          "size": 67541,
          "sha512": "2437404702b78f48f1fb76293992b93cbfca99b7bdea2501c4f8228535785730e2672a7c4f4e2441ce1539940b4613b05b4483ed6444474383d966a9453852f8",
          "sha256": "ef12f37c72fe20484583bfe8f10d795ed2ddd1de572ec7600cb36c1a284c3225",
          "sha1": "63b0b9ed3f8ef1001d61ae0b1873066130032ba4",
          "md5": "89bbde8466ab05952f6bfc3dff6a9647"
        }
      ]
    }
  ]
}
