{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "web-application",
    "version": "0.67.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.67.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.67.0.jar",
          "url": "web-application-0.67.0.jar",
          "size": 10584,
          "sha512": "70be8728633eced326d1554c33c3a4e47208706c5ea68376ce9211491a9bacc845cb3cc4e4bef00ac4ac4e5123fd8f7e86ae2d79500c7b99cfacff67d7c471b2",
          "sha256": "f6435d43962124948ee860a69d471521eec7923ceccffd9d3e63ab2a5724e1bf",
          "sha1": "fac6c15c3a2c13bab3906e182de04944068408db",
          "md5": "39fb5dbdbaa40a8425b38d900939e344"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.67.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "web-application-0.67.0.jar",
          "url": "web-application-0.67.0.jar",
          "size": 10584,
          "sha512": "70be8728633eced326d1554c33c3a4e47208706c5ea68376ce9211491a9bacc845cb3cc4e4bef00ac4ac4e5123fd8f7e86ae2d79500c7b99cfacff67d7c471b2",
          "sha256": "f6435d43962124948ee860a69d471521eec7923ceccffd9d3e63ab2a5724e1bf",
          "sha1": "fac6c15c3a2c13bab3906e182de04944068408db",
          "md5": "39fb5dbdbaa40a8425b38d900939e344"
        }
      ]
    }
  ]
}
