{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "ecosystem-plugin",
    "version": "0.125.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.6.0",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "web-application",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "library",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "spring",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "resource-packaging",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ecosystem-plugin-0.125.0.jar",
          "url": "ecosystem-plugin-0.125.0.jar",
          "size": 2902,
          "sha512": "0678dd7b5ebb77b86847c0bbdad2ec0665707ac83bea58e4c5b840bdd1171392287b8ac8e0c4ab504ee9efe5114c99633ced80114292dd0c7a324a628039ae5d",
          "sha256": "b47ddc55f4ef3af1d8487fba2ff41e8d09854e2e406474f73c22a1d47ed040a4",
          "sha1": "03be8dc10912a9b7b3b7dd09c7007e526390aa35",
          "md5": "380238e8d3050ccfeca5bed411d0f095"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.6.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "web-application",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "library",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "spring",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "resource-packaging",
          "version": {
            "requires": "0.125.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ecosystem-plugin-0.125.0.jar",
          "url": "ecosystem-plugin-0.125.0.jar",
          "size": 2902,
          "sha512": "0678dd7b5ebb77b86847c0bbdad2ec0665707ac83bea58e4c5b840bdd1171392287b8ac8e0c4ab504ee9efe5114c99633ced80114292dd0c7a324a628039ae5d",
          "sha256": "b47ddc55f4ef3af1d8487fba2ff41e8d09854e2e406474f73c22a1d47ed040a4",
          "sha1": "03be8dc10912a9b7b3b7dd09c7007e526390aa35",
          "md5": "380238e8d3050ccfeca5bed411d0f095"
        }
      ]
    }
  ]
}
