{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "jvm-application",
    "version": "0.102.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.102.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.102.0.jar",
          "url": "jvm-application-0.102.0.jar",
          "size": 66766,
          "sha512": "18bcc87c3a4611c26675086378caab277de1e680d873e2cad8f2aaa588791f9a313cc4568f94078c056dd8dc8f1f9cb9ff52c3b8840a04380fff480855179708",
          "sha256": "273fb95f2f152f50f68d6d9ffc43213adf6706e701a119b316655b8385a93e56",
          "sha1": "bdf8174ef266795a285f2e7240e0f029395883a1",
          "md5": "60d9d80040f0a2fbfc71c119d978c8b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.102.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-application-0.102.0.jar",
          "url": "jvm-application-0.102.0.jar",
          "size": 66766,
          "sha512": "18bcc87c3a4611c26675086378caab277de1e680d873e2cad8f2aaa588791f9a313cc4568f94078c056dd8dc8f1f9cb9ff52c3b8840a04380fff480855179708",
          "sha256": "273fb95f2f152f50f68d6d9ffc43213adf6706e701a119b316655b8385a93e56",
          "sha1": "bdf8174ef266795a285f2e7240e0f029395883a1",
          "md5": "60d9d80040f0a2fbfc71c119d978c8b0"
        }
      ]
    }
  ]
}
