{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.ecosystem",
    "module": "resource-packaging",
    "version": "0.94.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0-milestone-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.94.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.94.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.94.0.jar",
          "url": "resource-packaging-0.94.0.jar",
          "size": 28324,
          "sha512": "acfe2fa96c5b4ac0b67b2b5c8443192d953ef9f5abe9e595dba987edadd03fd913839565de9649c555666af29e3cb40b0b6d5e1cc2c8c715f49d35172b28b651",
          "sha256": "5dbc7cfbe59e4f77b69bd9d6c31c899fa0794c211338e483a348aeabd69a1096",
          "sha1": "a4ba40eca6fe23b317775c109de50a3018cf26b0",
          "md5": "772ee0bdfbca74931f597a4c79390a58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.ecosystem",
          "module": "common",
          "version": {
            "requires": "0.94.0"
          }
        },
        {
          "group": "org.jetbrains.ecosystem",
          "module": "jvm-application",
          "version": {
            "requires": "0.94.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "resource-packaging-0.94.0.jar",
          "url": "resource-packaging-0.94.0.jar",
          "size": 28324,
          "sha512": "acfe2fa96c5b4ac0b67b2b5c8443192d953ef9f5abe9e595dba987edadd03fd913839565de9649c555666af29e3cb40b0b6d5e1cc2c8c715f49d35172b28b651",
          "sha256": "5dbc7cfbe59e4f77b69bd9d6c31c899fa0794c211338e483a348aeabd69a1096",
          "sha1": "a4ba40eca6fe23b317775c109de50a3018cf26b0",
          "md5": "772ee0bdfbca74931f597a4c79390a58"
        }
      ]
    }
  ]
}
